import { CloseIcon } from "@/public/icons";
import Image from "next/image";
import about from "../public/images/about_img.png";
import Marquee from "react-fast-marquee";

const About = () => {
  return (
    <section className="padding-container pt-[60px] md:pt-[80px] xl:pt-[120px] text-white">
      <div className="relative md:pb-[36px] xl:pb-[40px]">
        <div className="md:flex gap-[48px] xl:gap-[85px] md:mb-[68px] md:mb-[56px]">
          <h2 className="font-grotesk extrabold-40 md:extrabold-60 xl:extrabold-120 uppercase mb-[16px] md:mb-0 md:min-w-[269px] xl:min-w-[538px]">
            a Story that started with{" "}
            <span className="text-primary">one simple ape</span>
          </h2>
          <p className="font-messina regular-16 text-right indent-[50%] md:indent-0 uppercase mb-[36px] xl:regular-24">
            WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW
            THE IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE <br />
            <span>YACHT</span>
          </p>
        </div>
        <div>
          <div className="flex flex-col text-center items-center gap-[16px] md:gap-[24px] xl:gap-[36px] md:w-[45%] md:w-[41%] mb-[40px] md:mb-0">
            <CloseIcon className="w-[24px] h-[24px] xl:w-[36px] xl:h-[36px]" />
            <p className="font-messina regular-12 md:regular-16 xl:regular-24 uppercase">
              EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS
              ARE RANDOMLY GENERATED BY USERS
            </p>
          </div>
          <div className="md:absolute right-0 bottom-0">
            <Image
              src={about}
              alt="NFT image"
              className="md:w-[313px] md:h-[422px] xl:w-[492px] xl:h-[662px]"
            />
          </div>
        </div>
      </div>
      <div className="ml-[-72px] md:ml-[-88px] xl:ml-[-212px] max-w-[1582px] w-screen bg-primary py-[8px] flex">
        <Marquee>
          <MarqueeText text="Destroy stereotypes" />
          <MarqueeText text="HAVE NO LIMITS" />
          <MarqueeText text="Break rules" />
        </Marquee>
      </div>
    </section>
  );
};

interface MarqueeTextProps {
  text: string;
}

const MarqueeText: React.FC<MarqueeTextProps> = ({ text }) => {
  return (
    <div className="flex items-center gap-[24px] xl:gap-[36px] mr-[36px]">
      <p className="extrabold-36 xl:extrabold-64 uppercase">{text}</p>
      <CloseIcon className="w-[36px] h-[36px]" />
    </div>
  );
};

export default About;
